config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :access_restrictions
  resources :access_restriction_types
  resources :database_headings
  resources :subheadings
  resources :sub_headings
  resources :headings
  resources :databases
  resources :vendors
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
end

app/views/home/index.html.erb
<nav>
  <%= link_to 'Vendors', vendors_path, class: "ml-2 rounded-lg py-3 px-5 bg-jhublue text-white inline-block font-medium" %>
  <%= link_to 'Databases', databases_path, class: "ml-2 rounded-lg py-3 px-5 bg-jhublue text-white inline-block font-medium" %>
  <%= link_to 'Headings', headings_path, class: "ml-2 rounded-lg py-3 px-5 bg-jhublue text-white inline-block font-medium" %>
  <%= link_to 'Subheadings', subheadings_path, class: "ml-2 rounded-lg py-3 px-5 bg-jhublue text-white inline-block font-medium" %>
  <%= link_to 'Database Headings', database_headings_path, class: "ml-2 rounded-lg py-3 px-5 bg-jhublue text-white inline-block font-medium" %>
  <%= link_to 'Access Restriction Types', access_restriction_types_path, class: "ml-2 rounded-lg py-3 px-5 bg-jhublue text-white inline-block font-medium" %>
  <%= link_to 'Access Restrictions', access_restrictions_path, class: "ml-2 rounded-lg py-3 px-5 bg-jhublue text-white inline-block font-medium" %>
</nav>