config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :access_restrictions
  resources :access_restriction_types
  resources :database_headings
  resources :subheadings
  resources :sub_headings
  resources :headings
  resources :databases
  resources :vendors
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/vendor.rb
# frozen_string_literal: true

class Vendor < ApplicationRecord
  validates :brand_name, uniqueness: true
  paginates_per 25
  include PgSearch::Model

  pg_search_scope :search_brand_name_asc, against: :brand_name,
                                          using: {
                                            tsearch: { prefix: true }
                                          }, order_within_rank: 'vendors.brand_name ASC'

  pg_search_scope :search_brand_name_desc, against: :brand_name,
                                           using: {
                                             tsearch: { prefix: true }
                                           }, order_within_rank: 'vendors.brand_name DESC'
end

app/controllers/vendors_controller.rb
# frozen_string_literal: true

# Controller for vendors
class VendorsController < ApplicationController
  before_action :set_vendor, only: %i[show edit update destroy]
  before_action :new_vendor, only: :create
  before_action :require_login

  # GET /vendors or /vendors.json
  def index # rubocop:disable Metrics/*
    if params[:search] && params[:sort].nil?
      @vendors ||= Vendor.search_brand_name_asc(params[:search]).page(params[:page])
    elsif params[:search] && params[:sort] == 'asc'
      @vendors ||= Vendor.search_brand_name_asc(params[:search]).page(params[:page])
    elsif params[:search] && params[:sort] == 'desc'
      @vendors ||= Vendor.search_brand_name_desc(params[:search]).page(params[:page])
    else
      @vendors = Vendor.all.order(brand_name: params[:sort] || :asc).page(params[:page])
    end
  end

  # GET /vendors/1 or /vendors/1.json
  def show; end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
    authorize! :create, @vendor
  end

  # GET /vendors/1/edit
  def edit
    authorize! :update, @vendor
  end

  # POST /vendors or /vendors.json
  def create
    authorize! :create, @vendor

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to vendor_url(@vendor), notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1 or /vendors/1.json
  def update
    authorize! :update, @vendor
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to vendor_url(@vendor), notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1 or /vendors/1.json
  def destroy
    authorize! :destroy, @vendor
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vendor
    @vendor = Vendor.find(params[:id])
  end

  def new_vendor
    @vendor = Vendor.new(vendor_params)
  end

  # Only allow a list of trusted parameters through.
  def vendor_params
    params.require(:vendor).permit(:brand_name)
  end

  # Require login
  def require_login
    redirect_to new_user_session_path if current_user.blank?
  end
end

app/views/vendors/_form.html.erb
<%= simple_form_for @vendor do |f| %>
  <%= f.input :brand_name, label: 'Brand Name' %>
  <%= f.button :submit %>
<% end %>

app/views/vendors/_vendor.html.erb
<div id="<%= dom_id vendor %>">
  <p class="my-5">
    <%= vendor.brand_name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to 'Show this vendor', vendor, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this vendor', edit_vendor_path(vendor), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/vendors/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing vendor</h1>

  <%= render "form", vendor: @vendor %>

  <%= link_to "Show this vendor", @vendor, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to vendors", vendors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/vendors/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Vendors</h1>
    <%= link_to 'New vendor', new_vendor_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex justify-between items-center">
    <%= form_tag('/vendors', :method => 'get') do %>
      <%= label_tag(:search, 'Search:', class: 'hidden') %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag('Search', class: 'rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium') %>
      <% if params[:search] %>
        <%= link_to 'Reset', vendors_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
      <% end %>
    <% end %>
  </div>

  <h2 class="mt-3">
    <% if params[:sort].nil? %>
      <%= link_to("Brand Name ▲", vendors_path(search: params[:search], sort: 'desc', )) %>
    <% end %>
    <% if params[:sort] == 'desc' %>
      <%= link_to("Brand Name ▼", vendors_path(search: params[:search], sort: 'asc', )) %>
    <% end %>
    <% if params[:sort] == 'asc' %>
      <%= link_to("Brand Name ▲", vendors_path(search: params[:search], sort: 'desc')) %>
    <% end %>
  </div>
  
  <div id="vendors" class="min-w-full">
    <%= render @vendors %>
    <%= paginate @vendors %>
  </div>
</div>

app/views/vendors/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New vendor</h1>

  <%= render "form", vendor: @vendor %>

  <%= link_to 'Back to vendors', vendors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/vendors/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @vendor %>

    <%= link_to 'Edit this vendor', edit_vendor_path(@vendor), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this vendor', vendor_path(@vendor), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to vendors', vendors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>