config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :access_restrictions
  resources :access_restriction_types
  resources :database_headings
  resources :subheadings
  resources :sub_headings
  resources :headings
  resources :databases
  resources :vendors
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/controllers/databases_controller.rb
# frozen_string_literal: true

# Controller for Databases
class DatabasesController < ApplicationController
  before_action :set_database, only: %i[show edit update destroy]
  before_action :new_database, only: :create
  before_action :require_login

  # GET /databases or /databases.json
  def index
    @databases = Database.all
  end

  # GET /databases/1 or /databases/1.json
  def show; end

  # GET /databases/new
  def new
    @database = Database.new
    authorize! :create, @database
  end

  # GET /databases/1/edit
  def edit
    authorize! :update, @database
  end

  # POST /databases or /databases.json
  def create
    authorize! :create, @database
    respond_to do |format|
      if @database.save
        format.html { redirect_to database_url(@database), notice: 'Database was successfully created.' }
        format.json { render :show, status: :created, location: @database }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @database.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /databases/1 or /databases/1.json
  def update
    authorize! :update, @database
    respond_to do |format|
      if @database.update(database_params)
        format.html { redirect_to database_url(@database), notice: 'Database was successfully updated.' }
        format.json { render :show, status: :ok, location: @database }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @database.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /databases/1 or /databases/1.json
  def destroy
    authorize! :destroy, @database
    @database.destroy

    respond_to do |format|
      format.html { redirect_to databases_url, notice: 'Database was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_database
    @database = Database.find(params[:id])
  end

  def new_database
    @database = Database.new(database_params)
  end

  # Only allow a list of trusted parameters through.
  def database_params
    params.require(:database).permit(:vendor_id, :jhu_id, :name, :url, :enable_proxy, :description, :internal_note)
  end

  # Require login
  def require_login
    redirect_to new_user_session_path if current_user.blank?
  end
end

app/views/databases/_database.html.erb
<div id="<%= dom_id database %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Vendor:</strong>
    <%= Vendor.find(database.vendor_id).brand_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= database.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">URL:</strong>
    <%= link_to(database.url, database.url) %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Enable proxy:</strong>
    <%= database.enable_proxy %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= database.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Internal note:</strong>
    <%= database.internal_note %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Headings:</strong>
    <%= database.headings.map { |h| h.label }.join(',') %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this database", database, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this database', edit_database_path(database), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/databases/_form.html.erb
<%= simple_form_for @database do |f| %>
  <%= f.association :vendor, label_method: :brand_name, value_method: :id, include_blank: false,  label: 'Vendor' %>
  <%= f.input :jhu_id, label: 'JHU ID' %>
  <%= f.input :name, label: 'Name' %>
  <%= f.input :url, label: 'URL' %>
  <%= f.input :enable_proxy, label: 'Enable Proxy?' %>
  <%= f.input :description, label: 'Description' %>
  <%= f.input :internal_note, label: 'Internal Note' %>
  <%= f.button :submit %>
<% end %>

app/views/databases/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing database</h1>

  <%= render "form", database: @database %>

  <%= link_to "Show this database", @database, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to databases", databases_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/databases/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Databases</h1>
    <%= link_to 'New database', new_database_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="databases" class="min-w-full">
    <%= render @databases %>
  </div>
</div>

app/views/databases/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New database</h1>

  <%= render "form", database: @database %>

  <%= link_to 'Back to databases', databases_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/databases/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @database %>

    <%= link_to 'Edit this database', edit_database_path(@database), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this database', database_path(@database), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to databases', databases_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>