config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :access_restrictions
  resources :access_restriction_types
  resources :database_headings
  resources :subheadings
  resources :sub_headings
  resources :headings
  resources :databases
  resources :vendors
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/subheading.rb
# frozen_string_literal: true

class Subheading < ApplicationRecord
end

app/controllers/subheadings_controller.rb
# frozen_string_literal: true

class SubheadingsController < ApplicationController
  before_action :set_subheading, only: %i[show edit update destroy]
  before_action :require_login

  # GET /subheadings or /subheadings.json
  def index
    @subheadings = Subheading.all
  end

  # GET /subheadings/1 or /subheadings/1.json
  def show; end

  # GET /subheadings/new
  def new
    @subheading = Subheading.new
  end

  # GET /subheadings/1/edit
  def edit; end

  # POST /subheadings or /subheadings.json
  def create
    @subheading = Subheading.new(subheading_params)

    respond_to do |format|
      if @subheading.save
        format.html { redirect_to subheading_url(@subheading), notice: 'Subheading was successfully created.' }
        format.json { render :show, status: :created, location: @subheading }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subheading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subheadings/1 or /subheadings/1.json
  def update
    respond_to do |format|
      if @subheading.update(subheading_params)
        format.html { redirect_to subheading_url(@subheading), notice: 'Subheading was successfully updated.' }
        format.json { render :show, status: :ok, location: @subheading }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subheading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subheadings/1 or /subheadings/1.json
  def destroy
    @subheading.destroy

    respond_to do |format|
      format.html { redirect_to subheadings_url, notice: 'Subheading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Require login
  def require_login
    redirect_to new_user_session_path if current_user.blank?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_subheading
    @subheading = Subheading.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subheading_params
    params.require(:subheading).permit(:label)
  end
end

app/helpers/subheadings_helper.rb
# frozen_string_literal: true

module SubheadingsHelper
end

app/views/subheadings/_form.html.erb
<%= form_with(model: subheading, class: "contents") do |form| %>
  <% if subheading.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(subheading.errors.count, "error") %> prohibited this subheading from being saved:</h2>

      <ul>
        <% subheading.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :label %>
    <%= form.text_field :label, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/subheadings/_subheading.html.erb
<div id="<%= dom_id subheading %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Label:</strong>
    <%= subheading.label %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this subheading", subheading, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this subheading', edit_subheading_path(subheading), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/subheadings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing subheading</h1>

  <%= render "form", subheading: @subheading %>

  <%= link_to "Show this subheading", @subheading, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to subheadings", subheadings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/subheadings/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Subheadings</h1>
    <%= link_to 'New subheading', new_subheading_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="subheadings" class="min-w-full">
    <%= render @subheadings %>
  </div>
</div>

app/views/subheadings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New subheading</h1>

  <%= render "form", subheading: @subheading %>

  <%= link_to 'Back to subheadings', subheadings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/subheadings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @subheading %>

    <%= link_to 'Edit this subheading', edit_subheading_path(@subheading), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this subheading', subheading_path(@subheading), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to subheadings', subheadings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>